#!/bin/bash

# red=$'\e[0;31m'
yel=$'\e[0;33m'
cyn=$'\e[0;36m'
grn=$'\e[0;32m'
end=$'\e[0m'

# Helpers
# -----------------------------------------------------------------------------
print_header() {
  printf "%s\\n===> %s \\n%s" "$cyn" "$1" "$end"
}

print_warn() {
  printf "%sWarn: $1%s\\n" "$yel" "$end"
}

print_success() {
  printf "%s$1%s\\n" "$grn" "$end"
}

append_to_file() {
  local file="$1"
  local text="$2"

  if ! grep -qs "^$text$" "$file"; then
    printf "\\n%s\\n" "$text" >> "$file"
  fi
}

brew_is_installed() {
  brew list -1 | grep -Fqx "$1"
}

tap_is_installed() {
  brew tap -1 | grep -Fqx "$1"
}

gem_install_or_update() {
  if gem list "$1" | grep "^$1 ("; then
    print_header "Updating $1"
    gem update "$@"
  else
    print_header "Installing $1"
    gem install "$@"
  fi
}

# Dirs
# -----------------------------------------------------------------------------
mkdir -p {"$HOME/code","$HOME/code_support"}

# Homebrew
# -----------------------------------------------------------------------------
print_header "Homebrew"
if ! command -v brew >/dev/null
then
    curl -fsSL \
      'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby

  print_success "Installation complete"
else
  print_warn "Already installed. Skipping"
fi

print_header "Brew-cask"
# https://github.com/caskroom/homebrew-cask/releases/tag/v0.60.0
if brew_is_installed 'brew-cask'
then
  print_header "Removing legacy brew-cask since its now part of caskroom/cask"
  brew uninstall --force 'brew-cask'
  print_success "Removal complete"
else
  print_warn "Already un-installed. Skipping"
fi

if tap_is_installed 'caskroom/versions'
then
  brew untap caskroom/versions
fi

# print_header "Updating Homebrew ..."
# cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update

print_header "Homebrew verification"
if brew doctor
then
  print_success "Installation is good to go"
else
  print_warn "Installation reported some errors or warnings"
fi

print_header "Brewfile"
# https://github.com/Homebrew/brew/issues/1151
brew update --force
if brew bundle --file="$HOME/Brewfile"
then
  print_success "All formulas and casks were installed successfully"
else
  print_warn "Some formulas or casks failed to install"
fi

print_header "Homebrew cleanup"
brew cleanup
brew cask cleanup

# Xcode
# -----------------------------------------------------------------------------
print_header "Xcode command line tools"
if xcode-select --install
then
  print_success "Installation complete"
else
  print_warn "Already installed. Skipping"
fi

# ASDF
# -----------------------------------------------------------------------------
print_header "ASDF version manager"
if [ ! -d "$HOME/.asdf" ]
then
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.4.1

  # shellcheck disable=SC1090
  source "$HOME/.asdf/asdf.sh"
  print_success "Installation complete"
else
  print_warn "Already installed. Skipping"
fi


install_asdf_plugin() {
  local name="$1"
  local url="$2"

  if ! asdf plugin-list | grep -Fq "$name"; then
    asdf plugin-add "$name" "$url"
  fi
}

install_asdf_language() {
  local language="$1"
  local latest_available
  latest_available="$(asdf list-all "$language" | grep -v '[A-Za-z-]' | tail -1)"
  local version="${2:-$latest_available}"

  if ! asdf list "$language" | grep -Fq "$version"
  then
    asdf install "$language" "$version"
    asdf global "$language" "$version"
  else
    print_warn "Version $version already installed"
  fi
}

install_asdf_plugin "ruby" "https://github.com/asdf-vm/asdf-ruby.git"
install_asdf_plugin "nodejs" "https://github.com/asdf-vm/asdf-nodejs.git"
install_asdf_plugin "erlang" "https://github.com/asdf-vm/asdf-erlang.git"
install_asdf_plugin "elixir" "https://github.com/asdf-vm/asdf-elixir.git"
install_asdf_plugin "python" "https://github.com/tuvistavie/asdf-python.git"
install_asdf_plugin "golang" "https://github.com/kennyp/asdf-golang.git"

print_header "Ruby"
install_asdf_language "ruby"

print_header "Node"
# Import the Node.js release team's OpenPGP keys to main keyring:
bash "$HOME/.asdf/plugins/nodejs/bin/import-release-team-keyring"
install_asdf_language "nodejs"

print_header "Erlang"
install_asdf_language "erlang" "20.0"

print_header "Elixir"
install_asdf_language "elixir"

print_header "Python"
install_asdf_language "python"

print_header "Golang"
install_asdf_language "golang"

# Rubygems and Bundler
# -----------------------------------------------------------------------------
print_header "Rubygems"
gem update --system

print_header "Bundler"
gem_install_or_update "bundler"

print_header "Bundle jobs config"
number_of_cores=$(sysctl -n hw.ncpu)
bundle config --global jobs $((number_of_cores - 1))

# Powerline fonts
# -----------------------------------------------------------------------------
print_header "Powerline Fonts"
if [ ! -d "$HOME/code_support/fonts" ]
then
  git clone https://github.com/powerline/fonts.git --depth=1 "$HOME/code_support/fonts"

  ~/code_support/fonts/install.sh

  print_success "Installation complete"
else
  print_warn "Already installed. Skipping"
fi

# Oh-my-zsh
# -----------------------------------------------------------------------------
print_header "Oh-my-zsh"
if [ ! -d "$HOME/.oh-my-zsh" ]
then
  cd || true
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

  print_success "Installation complete"
else
  print_warn "Already installed. Skipping"
fi

# Dotfiles
# -----------------------------------------------------------------------------
print_header "Dotfiles"
if [ ! -d "$HOME/code_support/dotfiles" ]
then
  dotfiles="$HOME/code_support/dotfiles"
  git clone https://github.com/jasonpilz/dotfiles.git "$dotfiles"
  passive=(
    agignore
    aliases
    gitignore_global
    gvimrc
    htoprc
    hyper.js
    iex.exs
    pryrc
    rspec
    tmux.conf
    vimrc
  )

  force=(
    zshrc
  )

  for dotfile in "${passive[@]}"; do
    ln -s "$dotfiles/$dotfile" "$HOME/.$dotfile"
  done

  for dotfile in "${force[@]}"; do
    ln -sf "$dotfiles/$dotfile" "$HOME/.$dotfile"
  done

  ln -s "$dotfiles/karabiner" "$HOME/.config"

  print_success "Installation complete"
else
  print_warn "Already installed. Skipping"
fi

# Vundle and install plugins
# -----------------------------------------------------------------------------
print_header "Vundle"
if [ ! -d "$HOME/.vim/bundle/Vundle.vim" ]
then
  git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

  vim +PluginInstall +qall
  print_success "Installation and plugin install complete"
else
  print_warn "Already installed. Skipping"
fi

# Gotham theme for iterm2
# -----------------------------------------------------------------------------
print_header "Gotham-contrib"
if [ ! -d "$HOME/code_support/gotham-contrib-master" ]
then
  dest_zipfile="gotham-contrib.zip"

  cd "$HOME/code_support" || true

  wget https://github.com/whatyouhide/iterm2-gotham/archive/master.zip
  mv master.zip "$dest_zipfile"
  unzip "$dest_zipfile"
  rm "$dest_zipfile"

  open ./gotham-contrib-master/iterm2/Gotham.itermcolors

  print_success "Installation complete"
else
  print_warn "Already installed. Skipping"
fi

# Support split DNS with openconnect
# -----------------------------------------------------------------------------
print_header "Split DNS"
if [ ! -f /usr/local/etc/vpnc-script.bak ]
then
  mv /usr/local/etc/vpnc-script /usr/local/etc/vpnc-script.bak
  curl "https://raw.githubusercontent.com/batmanppc/vpnc-scripts/43e21edbf1683804f08364cef7269ed7bc81687c/vpnc-script" \
    > /usr/local/etc/vpnc-script
  chmod +x /usr/local/etc/vpnc-script

  print_success "Configuration complete"
else
  print_warn "Already configured. Skipping"
fi

# Customizations
# -----------------------------------------------------------------------------
print_header "Overrides from ~/.laptop.local"
if [ -f "$HOME/.laptop.local" ]
then
  # shellcheck disable=SC1090
  . "$HOME/.laptop.local"
else
  print_warn "No ~/.laptop.local file available. Skipping"
fi
