#!/bin/bash

# Helpers
# -----------------------------------------------------------------------------
fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC1117
  printf "\n$fmt\n" "$@"
}

append_to_file() {
  local file="$1"
  local text="$2"

  if ! grep -qs "^$text$" "$file"; then
    printf "\n%s\n" "$text" >> "$file"
  fi
}

brew_is_installed() {
  brew list -1 | grep -Fqx "$1"
}

tap_is_installed() {
  brew tap -1 | grep -Fqx "$1"
}

gem_install_or_update() {
  if gem list "$1" | grep "^$1 ("; then
    fancy_echo "Updating %s ..." "$1"
    gem update "$@"
  else
    fancy_echo "Installing %s ..." "$1"
    gem install "$@"
  fi
}

# DOTFILES
# -----------------------------------------------------------------------------


# XCode
# -----------------------------------------------------------------------------
if xcode-select --install
then
  fancy_echo "Installed xcode commandline tools."
else
  fancy_echo "xcode commandline tools already installed. Skipping ..."
fi

# HOMEBREW
# -----------------------------------------------------------------------------
if ! command -v brew >/dev/null
then
  fancy_echo "Installing Homebrew ..."
    curl -fsSL \
      'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby

    # shellcheck disable=SC2016
    # append_to_file "$shell_file" 'export PATH="/usr/local/bin:$PATH"'
else
  fancy_echo "Homebrew already installed. Skipping ..."
fi

# https://github.com/caskroom/homebrew-cask/releases/tag/v0.60.0
if brew_is_installed 'brew-cask'
then
  fancy_echo "Removing legacy brew-cask since its now part of caskroom/cask ..."
  brew uninstall --force 'brew-cask'
fi

if tap_is_installed 'caskroom/versions'
then
  brew untap caskroom/versions
fi

# fancy_echo "Updating Homebrew ..."
# cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update

fancy_echo "Verifying the Homebrew installation..."
if brew doctor
then
  fancy_echo "Your Homebrew installation is good to go."
else
  fancy_echo "Your Homebrew installation reported some errors or warnings."

  echo "Review the Homebrew messages to see if any action is needed."
fi

fancy_echo "Installing formulas and casks from the Brewfile ..."
# https://github.com/Homebrew/brew/issues/1151
brew update --force
if brew bundle --file="$HOME/Brewfile"
then
  fancy_echo "All formulas and casks were installed successfully."
else
  fancy_echo "Some formulas or casks failed to install."

  echo "This is usually due to one of the Mac apps being already installed,"
  echo "in which case, you can ignore these errors."
fi

fancy_echo "Cleaning up old Homebrew formulae ..."
brew cleanup
brew cask cleanup
